export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;

export const RECORDS_ID = process.env.NEXT_PUBLIC_APPWRITE_RECORDS_ID!;
export const BILLINGS_ID = process.env.NEXT_PUBLIC_APPWRITE_BILLINGS_ID!;
export const BILLING_OPTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_BILLING_OPTIONS_ID!;

export const INVITES_ID = process.env.NEXT_PUBLIC_APPWRITE_INVITES_ID!;
export const NOTES_ID = process.env.NEXT_PUBLIC_APPWRITE_NOTES_ID!;
export const MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGES_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;

export const PRICING_ID = process.env.NEXT_PUBLIC_APPWRITE_PRICING_ID!;

export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY!
