export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
export const TASK_ASSIGNEES_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_ASSIGNEES_ID!;
export const TASK_SHARES_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_SHARES_ID!;
export const TASK_COMMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_COMMENTS_ID!
export const TASK_ACTIVITY_LOGS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASK_ACTIVITY_LOGS_ID!

export const USER_HOME_CONFIG_ID = process.env.NEXT_PUBLIC_APPWRITE_USER_HOME_CONFIG_ID!

export const RECORD_TABLES_ID = process.env.NEXT_PUBLIC_APPWRITE_RECORD_TABLES_ID!;
export const RECORDS_ID = process.env.NEXT_PUBLIC_APPWRITE_RECORDS_ID!;
export const BILLINGS_ID = process.env.NEXT_PUBLIC_APPWRITE_BILLINGS_ID!;
export const BILLING_OPTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_BILLING_OPTIONS_ID!;

export const INVITES_ID = process.env.NEXT_PUBLIC_APPWRITE_INVITES_ID!;
export const NOTES_ID = process.env.NEXT_PUBLIC_APPWRITE_NOTES_ID!;
export const MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGES_ID!;
export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
export const FILES_ID = process.env.NEXT_PUBLIC_APPWRITE_FILES_ID!

export const CONTACT_US_MESSAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_CONTACT_US_MESSAGES_ID!

export const MEETS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEETS_ID!

export const CHECKLIST_ITEMS_ID = process.env.NEXT_PUBLIC_APPWRITE_CHECKLIST_ITEMS_ID!
export const CHECKLIST_ITEM_ASSIGNEES_ID = process.env.NEXT_PUBLIC_APPWRITE_CHECKLIST_ITEM_ASSIGNEES_ID!

export const PRICING_ID = process.env.NEXT_PUBLIC_APPWRITE_PRICING_ID!;
export const ROLES_PERMISSIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_ROLES_PERMISSIONS_ID!;

export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY!


export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
export const GOOGLE_REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI

export const GROQ_API_KEY = process.env.GROQ_API_KEY!

export const NEXT_PUBLIC_APP_URL = process.env.NEXT_PUBLIC_APP_URL //change app to origin?